### ISSUE TITLE
@everyone this is fucking urgent.

### ISSUE THREAD

**Issue by Sorracha-A** [kaikaew13/moneymate#2]
🚨🚨🚨
The owner of this GitHub repository has gone missing. An urgent search operation is underway for my friend who seems to have mysteriously vanished. The last known words he uttered were, "I'm not hungry" – which I suspect might be a secret code to locate him. If anyone finds him, please contact me immediately.

https://github.com/kaikaew13/moneymate/assets/90688030/a735b34c-47f6-45a3-b6c7-710b03083856
________________________________________________________________________________________________________________
# Relevant photos

## Front
![IMG_1033](https://github.com/kaikaew13/moneymate/assets/90688030/ecbdfcbb-00ec-4ef5-9b81-c9c90bbbc9d2)
## Side
![IMG_1034](https://github.com/kaikaew13/moneymate/assets/90688030/3eec6b25-c108-4eaa-8098-ac3dced064fa)
## Back
![IMG_1035](https://github.com/kaikaew13/moneymate/assets/90688030/d98d794c-ef25-4333-baad-fce65a4d30bb)
## Side
![IMG_1036](https://github.com/kaikaew13/moneymate/assets/90688030/e417a3d9-b46c-4092-bf69-e8369c7a5cf1)

**Comment by kaikaew13** [comment]
Hello 🤗, I'm still here! Since I'm already I will proceed to close this issue 😼
